version: "2"

services:
    app:
        image: bernardosecades/warning-shot
        container_name: warning_shot
        env_file:
        - local.env
#        volumes:
#        - "${PWD}/:/app"
        ports:
        - "3000:3000"
        environment:
        - PORT=7000
    db:
        image: bernardosecades/warning-shot-db
        container_name: warning_shot_db
        ports:
        - "3306:3306"

networks:
    default:
        external:
            name: dev-network
